version: '3.4'

services:
  _base:
    &base
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/code
      - ~/.gitconfig:/root/.gitconfig

  # a fully loaded development environment to test new code
  dev:
    <<: *base
    command: /bin/bash/

  jupyter:
    <<: *base
    entrypoint: "jupyter-lab"
    ports:
      - "8888:8888"
    command: ["--ip", "0.0.0.0", "--allow-root"]
